import type { TrainingPlan } from "../types";

/** Builds a human-readable Markdown representation of a training plan. */
export function planToMarkdown(plan: TrainingPlan): string {
  const lines: string[] = [];
  const { overview, weeklySchedule, progression } = plan;

  lines.push("# GymAI Dhaka — Training Plan");
  lines.push("");
  lines.push(`- **Goal:** ${overview.goal}`);
  lines.push(`- **Frequency:** ${overview.frequency}`);
  lines.push(`- **Split:** ${overview.split}`);
  lines.push(`- **Version:** ${plan.version}`);
  lines.push(`- **Created:** ${new Date(plan.createdAt).toLocaleDateString("en-US")}`);
  lines.push("");
  lines.push("## Program Notes");
  lines.push("");
  lines.push(overview.notes);
  lines.push("");

  weeklySchedule.forEach((day) => {
    lines.push(`## ${day.day} — ${day.focus}`);
    lines.push("");
    if (day.exercises.length === 0) {
      lines.push("_Rest / active recovery_");
      lines.push("");
      return;
    }
    lines.push("| # | Exercise | Sets × Reps | Rest | RPE | Notes |");
    lines.push("|---|---|---|---|---|---|");
    day.exercises.forEach((ex, idx) => {
      const notes = [ex.notes, ex.alternatives?.length ? `Alt: ${ex.alternatives.join(", ")}` : ""]
        .filter(Boolean)
        .join(" — ");
      lines.push(
        `| ${idx + 1} | ${ex.name} | ${ex.sets} × ${ex.reps} | ${ex.rest} | ${ex.rpe} | ${notes || "—"} |`,
      );
    });
    lines.push("");
  });

  lines.push("## Progression Strategy");
  lines.push("");
  lines.push(progression);
  lines.push("");
  lines.push("---");
  lines.push("_Generated by GymAI Dhaka — free AI training plans for everyone in Dhaka._");
  lines.push("");

  return lines.join("\n");
}

/** Copies the plan as Markdown to the clipboard (with a graceful fallback). */
export async function copyPlanAsMarkdown(plan: TrainingPlan): Promise<boolean> {
  const markdown = planToMarkdown(plan);
  try {
    if (navigator.clipboard?.writeText) {
      await navigator.clipboard.writeText(markdown);
      return true;
    }
  } catch {
    // fall through to legacy path
  }
  try {
    const ta = document.createElement("textarea");
    ta.value = markdown;
    ta.style.position = "fixed";
    ta.style.opacity = "0";
    document.body.appendChild(ta);
    ta.select();
    const ok = document.execCommand("copy");
    document.body.removeChild(ta);
    return ok;
  } catch {
    return false;
  }
}

/** Opens a print-friendly view of the plan using the browser print dialog. */
export function printPlan(plan: TrainingPlan): void {
  const markdown = planToMarkdown(plan);
  const html = markdown
    .split("\n")
    .map((line) => {
      const escaped = line
        .replace(/&/g, "&amp;")
        .replace(/</g, "&lt;")
        .replace(/>/g, "&gt;");
      return `<div>${escaped || "&nbsp;"}</div>`;
    })
    .join("");
  const win = window.open("", "_blank", "width=800,height=900");
  if (!win) return;
  win.document.write(
    `<!doctype html><html><head><title>GymAI Training Plan</title>` +
      `<style>body{font-family:system-ui,sans-serif;padding:32px;line-height:1.6;}` +
      `div{white-space:pre-wrap}@media print{body{padding:0}}</style></head>` +
      `<body>${html}</body></html>`,
  );
  win.document.close();
  win.focus();
  setTimeout(() => win.print(), 250);
}
